# .pre-commit-config.yaml
# Monorepo structure: backend/ and frontend/ directories
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=5000"]
      - id: check-merge-conflict

  # Python linting for backend
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.5
    hooks:
      - id: ruff-format
        args: ["--config=backend/pyproject.toml"]
        files: ^backend/.*\.py$
        exclude: '\.backup\.py$'
      - id: ruff
        args: ["--fix", "--config=backend/pyproject.toml"]
        files: ^backend/.*\.py$
        exclude: '\.backup\.py$'

  # Python type checking for backend
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]
        files: ^backend/src/service/
        additional_dependencies: ["sqlalchemy", "pydantic"]
        types: [python]

  # Frontend code quality (using local tools)
  - repo: local
    hooks:
      # Prettier formatting for frontend
      - id: prettier-frontend
        name: prettier (frontend)
        entry: bash -c 'cd frontend && for file in "$@"; do node_modules/.bin/prettier --write "${file#frontend/}"; done' --
        language: system
        files: ^frontend/.*\.(js|svelte|json|css|html)$
        exclude: ^frontend/(node_modules|dist|build)/
        pass_filenames: true

      # ESLint for frontend JavaScript/Svelte
      - id: eslint-frontend
        name: eslint (frontend)
        entry: bash -c 'cd frontend && for file in "$@"; do node_modules/.bin/eslint "${file#frontend/}"; done' --
        language: system
        files: ^frontend/.*\.(js|svelte)$
        exclude: ^frontend/(node_modules|dist|build)/
        pass_filenames: true
